---
# roles/test-scripts/tasks/main.yml

- name: Create test scripts directory
  file:
    path: /usr/local/bin
    state: directory
    mode: '0755'

- name: Deploy IPsec test script
  template:
    src: test-ipsec.sh.j2
    dest: /usr/local/bin/test-ipsec.sh
    mode: '0755'

- name: Deploy continuous traffic script
  template:
    src: continuous-traffic.sh.j2
    dest: /usr/local/bin/continuous-traffic.sh
    mode: '0755'

- name: Create README on server
  template:
    src: README.md.j2
    dest: /home/{{ ansible_user }}/README.md
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
